services:
  postgres:
    image: 'ankane/pgvector:latest'
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'Yassine123'
      POSTGRES_DB: 'postgres'

    logging:
      options:
        max-size: '10m'
        max-file: '3'
    ports:
      - '5434:5432'
    healthcheck:
      test: ['CMD','pg_isready', '-U', 'postgres', '-h', 'localhost', '-p', '5432']
      interval: 2s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'Yassine123'
    volumes:
      - './server.json:/pgadmin4/servers.json'
    ports:
      - '5050:80'
      